apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-configmap-reload-new
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-configmap-reload-new
  template:
    metadata:
      labels:
        app: kubernetes-configmap-reload-new
    spec:
      containers:
        - name: kubernetes-configmap-reload-new
          image: jaik/kubernetes-configmap-reload-new:latest
